kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {
\n stage 'buildInDevelopment'
\n stage 'deployInDevelopment'
\n stage 'deployInTesting'
}"
