node('maven') {
  
def mvnCmd = "mvn -s configuration/cicd-settings.xml"
sh "${mvnCmd} -v"
  
stage ('buildInDevelopment')
{  
git branch: 'binary', url: 'https://github.com/shrishs/openshift-jee-sample.git'
sh "${mvnCmd} -e -Popenshift clean install -DskipTests=true"
}  
stage ('Push to Nexus') {
sh "${mvnCmd} -e -Popenshift deploy -DskipTests=true"
}  
stage 'deployInDevelopment'
stage 'deployInTesting'
}
